name: "testestestset"
inputs:
   github-repo-url:
      description: "project github repository url"
      required: true
      default: ''
runs:
   using: "docker"
   image: "Dockerfile"
   args:
      - ${{ inputs.github-repo-url }}