name: "testestestset"
inputs:
   github-repo-url:
      description: "project github repository url"
      required: true
      default: ''
   github-user-id:
      required: true
      default: ''
   gh-token:
      required: true
      default: ''
runs:
   using: "docker"
   image: "Dockerfile"
   args:
      - ${{ inputs.github-repo-url }}
      - ${{ inputs.github-user-id }}
      - ${{ inputs.gh-token }}